python toutf8.py -d browser_modules/
python toutf8.py -d libExt/
python toutf8.py -d libNCUI/
python toutf8.py -d libResource/
python toutf8.py -d libsExt/
python toutf8.py -d NCUI/
python toutf8.py -d NCUI-DEV/
python toutf8.py -d node-runner/
python toutf8.py -d plugins/
python toutf8.py -d startup/